code --install-extension 2gua.rainbow-brackets
code --install-extension 766b.go-outliner
code --install-extension aaron-bond.better-comments
code --install-extension ahmadalli.vscode-nginx-conf
code --install-extension ajshortt.tokyo-hack
code --install-extension alefragnani.Bookmarks
code --install-extension anseki.vscode-color
code --install-extension arcticicestudio.nord-visual-studio-code
code --install-extension azemoh.one-monokai
code --install-extension banxi.go-snippets
code --install-extension bhshawon.node-json-autocomplete
code --install-extension bierner.docs-view
code --install-extension bierner.lit-html
code --install-extension bierner.markdown-preview-github-styles
code --install-extension bungcip.better-toml
code --install-extension christian-kohler.npm-intellisense
code --install-extension cschleiden.vscode-github-actions
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension deerawan.vscode-dash
code --install-extension DotJoshJohnson.xml
code --install-extension dracula-theme.theme-dracula
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension eg2.vscode-npm-script
code --install-extension EliverLara.andromeda
code --install-extension emilast.LogFileHighlighter
code --install-extension Equinusocio.vsc-community-material-theme
code --install-extension Equinusocio.vsc-material-theme
code --install-extension equinusocio.vsc-material-theme-icons
code --install-extension esbenp.prettier-vscode
code --install-extension fisheva.eva-theme
code --install-extension foxundermoon.shell-format
code --install-extension gerane.Theme-FlatlandMonokai
code --install-extension ginfuru.ginfuru-better-solarized-dark-theme
code --install-extension golang.go
code --install-extension Gruntfuggly.todo-tree
code --install-extension GulajavaMinistudio.mayukaithemevsc
code --install-extension hashicorp.terraform
code --install-extension hoovercj.ruby-linter
code --install-extension humao.rest-client
code --install-extension jasonnutter.search-node-modules
code --install-extension johnpapa.winteriscoming
code --install-extension jolaleye.horizon-theme-vscode
code --install-extension matklad.rust-analyzer
code --install-extension mhutchie.git-graph
code --install-extension michelemelluso.code-beautifier
code --install-extension mikestead.dotenv
code --install-extension monokai.theme-monokai-pro-vscode
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension ms-python.python
code --install-extension ms-toolsai.jupyter
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.vscode-typescript-tslint-plugin
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension ms-vsliveshare.vsliveshare-audio
code --install-extension ms-vsliveshare.vsliveshare-pack
code --install-extension msyrus.go-doc
code --install-extension onsi.vscode-ginkgo
code --install-extension PandaDigitalLLC.panda-dark
code --install-extension Pivotal.vscode-spring-boot
code --install-extension PKief.material-icon-theme
code --install-extension raynigon.nginx-formatter
code --install-extension rebornix.ruby
code --install-extension redhat.java
code --install-extension redhat.vscode-xml
code --install-extension redhat.vscode-yaml
code --install-extension RobbOwen.synthwave-vscode
code --install-extension rokoroku.vscode-theme-darcula
code --install-extension rust-lang.rust
code --install-extension ryanluker.vscode-coverage-gutters
code --install-extension sanity-io.vscode-sanity
code --install-extension sdras.night-owl
code --install-extension selzoc.ginkgo-lens
code --install-extension serayuzgur.crates
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension sleistner.vscode-fileutils
code --install-extension softwaredotcom.swdc-vscode
code --install-extension spmeesseman.vscode-taskexplorer
code --install-extension steoates.autoimport
code --install-extension stoplight.spectral
code --install-extension teabyii.ayu
code --install-extension thegeoffstevens.best-dark-themes-pack
code --install-extension tinkertrain.theme-panda
code --install-extension tlevesque.import-to-require
code --install-extension tootone.org-mode
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension vscjava.vscode-spring-boot-dashboard
code --install-extension vscode-icons-team.vscode-icons
code --install-extension vscodevim.vim
code --install-extension WakaTime.vscode-wakatime
code --install-extension wesbos.theme-cobalt2
code --install-extension whizkydee.material-palenight-theme
code --install-extension william-voyek.vscode-nginx
code --install-extension wingrunr21.vscode-ruby
code --install-extension wix.vscode-import-cost
code --install-extension xabikos.JavaScriptSnippets
code --install-extension XadillaX.viml
code --install-extension zhuangtongfa.material-theme
code --install-extension zsh.go-snippets
