code --install-extension 766b.go-outliner
code --install-extension bhshawon.node-json-autocomplete
code --install-extension bierner.lit-html
code --install-extension christian-kohler.npm-intellisense
code --install-extension dbaeumer.vscode-eslint
code --install-extension DotJoshJohnson.xml
code --install-extension eamodio.gitlens
code --install-extension esbenp.prettier-vscode
code --install-extension Gruntfuggly.todo-tree
code --install-extension hoovercj.ruby-linter
code --install-extension jasonnutter.search-node-modules
code --install-extension mhutchie.git-graph
code --install-extension michelemelluso.code-beautifier
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.Go
code --install-extension ms-vscode.vscode-typescript-tslint-plugin
code --install-extension msyrus.go-doc
code --install-extension Pivotal.vscode-spring-boot
code --install-extension rebornix.ruby
code --install-extension redhat.java
code --install-extension ryanluker.vscode-coverage-gutters
code --install-extension tlevesque.import-to-require
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension vscjava.vscode-spring-boot-dashboard
code --install-extension vscodevim.vim
