nnoremap d "_d
nnoremap c "_c
nnoremap x "_x
nnoremap <leader>c c
nnoremap <leader>d d
nnoremap <leader>x x
vnoremap d "_d
vnoremap c "_c
vnoremap x "_x
vnoremap p "_dP
vnoremap <leader>c c
vnoremap <leader>d d
vnoremap <leader>x x
vnoremap <leader>p p
nnoremap C-p :Files